export enum Techs {
    JAVASCRIPT = 'javascript',
    REACTJS = 'reactjs',
    NODEJS = 'nodejs',
    TAILWINDCSS = 'tailwindcss',
    MATERIALUI = 'materialui',
    TYPESCRIPT = 'typescript',
    NEXTJS = 'nextjs',
    PYTHON = 'python',
    GOLANG = 'golang',
    FLASK = 'flask',
    DJANGO = 'django',
    GIT = 'git',
    MONGODB = 'mongodb',
    MYSQL = 'mysql',
    POSTGRESQL = 'postgresql',
    EXPRESS = 'express',
    NESTJS = 'nestjs',
    CSSMODULES = 'cssmodules'
}