import type { Metadata } from 'next'
import NavBar from '@/components/navbar/NavBar'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="bg-black text-white w-full p-5 md:p-10 lg:p-20 flex items-center flex-col justify-between mt-[100px]">
        <NavBar />
        {children}
      </body>
    </html>
  )
}
